version: "3"

services:
  api:
    build:
      dockerfile: ./Dockerfile
    container_name: ui
    restart: unless-stopped
    ports:
      - 8088:8088
    env_file:
      - ./_env.production.local
    environment:
      - PORT=8088

volumes:
  db:
  cache:
